import type { Metadata } from "next";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app/sidebar";
import { AppHeader } from "@/components/app/header";
import { requireSession } from "@/lib/session";
import { cookies } from "next/headers";

export const runtime = "nodejs";

export const metadata: Metadata = {
  title: "Unlock Auto",
  description: "Generated by create next app",
};

export default async function AppLayout({
  sidebar,
  header,
  children,
}: Readonly<{
  header: React.ReactNode;
  sidebar: React.ReactNode;
  children: React.ReactNode;
}>) {
  const [session, cookieStore] = await Promise.all([
    requireSession(),
    cookies(),
  ]);

  return (
    <>
      <SidebarProvider>
        <AppSidebar sidebar={sidebar} user={session?.user} />
        <SidebarInset>
          <AppHeader />
          {children}
        </SidebarInset>
      </SidebarProvider>
    </>
  );
}
